import os
import shutil
import tempfile
import uuid
import logging
import subprocess
from fastapi import FastAPI, File, UploadFile, BackgroundTasks, HTTPException
from fastapi.responses import FileResponse
from fastapi.middleware.cors import CORSMiddleware

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

app = FastAPI(title="PDFlow Secure Backend Services")

# Allow requests from Next.js frontend
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000", "https://pdflow.in", "*"],
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)

def cleanup_files(*file_paths):
    """Securely deletes temporary files after the response is sent."""
    for file_path in file_paths:
        try:
            if os.path.exists(file_path):
                if os.path.isdir(file_path):
                    shutil.rmtree(file_path)
                else:
                    os.remove(file_path)
                logger.info(f"Securely wiped: {file_path}")
        except Exception as e:
            logger.error(f"Error wiping {file_path}: {e}")

@app.get("/")
def read_root():
    return {"status": "Secure PDFlow API is running"}

@app.post("/api/convert/pdf-to-word")
async def convert_pdf_to_word(background_tasks: BackgroundTasks, file: UploadFile = File(...)):
    if not file.filename.lower().endswith(".pdf"):
        raise HTTPException(status_code=400, detail="File must be a PDF")

    # Create a secure temporary directory
    temp_dir = tempfile.mkdtemp()
    
    # Generate unique filenames
    unique_id = str(uuid.uuid4())
    pdf_filename = f"{unique_id}.pdf"
    pdf_path = os.path.join(temp_dir, pdf_filename)
    output_dir = os.path.join(temp_dir, "output")
    os.makedirs(output_dir, exist_ok=True)
    
    try:
        # Read and save the uploaded PDF securely
        content = await file.read()
        with open(pdf_path, "wb") as f:
            f.write(content)
        
        logger.info(f"Processing PDF to Word via PP-Structure: {file.filename}")
        
        # Run PaddleOCR PP-Structure via CLI
        # --image_dir: input pdf
        # --type: structure (for layout recovery)
        # --recovery: true (to generate DOCX)
        # --use_pdf2docx: true
        # --output: our secure temp output dir
        command = [
            "paddleocr",
            "--image_dir", pdf_path,
            "--type", "structure",
            "--recovery", "true",
            "--use_pdf2docx", "true",
            "--output", output_dir
        ]
        
        # Execute the command
        process = subprocess.run(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
        
        if process.returncode != 0:
            logger.error(f"PaddleOCR Error: {process.stderr}")
            raise Exception("PaddleOCR processing failed.")
            
        # The DOCX file should be generated inside output_dir/<unique_id>/<unique_id>.docx
        # or output_dir/<unique_id>_ocr.docx. We will search for any .docx in the output_dir.
        docx_path = None
        for root, dirs, files in os.walk(output_dir):
            for f in files:
                if f.endswith(".docx"):
                    docx_path = os.path.join(root, f)
                    break
            if docx_path:
                break
                
        if not docx_path or not os.path.exists(docx_path):
            raise Exception("DOCX file was not generated by PaddleOCR.")

        # Cleanup is scheduled to run AFTER the response is sent to ensure Zero-Retention
        background_tasks.add_task(cleanup_files, temp_dir)

        # Return the DOCX file
        base_name = os.path.splitext(file.filename)[0]
        return FileResponse(
            docx_path, 
            media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document", 
            filename=f"{base_name}_converted.docx"
        )

    except Exception as e:
        # If an error occurs, clean up immediately
        cleanup_files(temp_dir)
        logger.error(f"Error during conversion: {e}")
        raise HTTPException(status_code=500, detail="Error during PDF conversion. Please try again.")
